spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/departmentmanagementdev
    password: karan
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to Our New Spring Boot Learning Tuturialssss
server:
  port: '1010'
