spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/relation-mapping-spring-data-jpa
    password: karan
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
  profiles:
    active: default
server:
  port: '1010'
welcome:
 message: Welcome to spring boot tutorial
 
management:
      endpoints:
        web:
          exposure:
            include: "*"
            exclude: "beans,env" # this is to exclude endpoints from actuator
